config/routes.rb
Rails.application.routes.draw do
  root to: 'customers#index'
  resources :customers
  resources :orders
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders

  validates :first_name, presence: true, format: { with: /\A[a-z\-' ]+\z/i }
  validates :last_name, presence: true, format: { with: /\A[a-z\-' ]+\z/i }
  validates :phone, presence: true
  validates :phone, numericality: { only_integer: true }
  validates :phone, length: { is: 10 }
  validates :email, presence: true, email: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  validates_associated :customer
  validates :product_name, presence: true
  validates :product_count, presence: true
  validates :product_count, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found

  before_action :set_customer, only: %i[ show edit update destroy ]

  # layout 'customer_layout'

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    # @customer = Customer.new(customer_params)
    #
    # respond_to do |format|
    #   if @customer.save
    #     format.html { redirect_to customer_url(@customer), notice: "Customer was successfully created." }
    #     format.json { render :show, status: :created, location: @customer }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @customer.errors, status: :unprocessable_entity }
    #   end
    # end
    @customer = Customer.new(customer_params)
    if @customer.save
      flash.notice = "The customer record was created successfully."
      redirect_to @customer
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    # respond_to do |format|
    #   if @customer.update(customer_params)
    #     format.html { redirect_to customer_url(@customer), notice: "Customer was successfully updated." }
    #     format.json { render :show, status: :ok, location: @customer }
    #   else
    #     format.html { render :edit, status: :unprocessable_entity }
    #     format.json { render json: @customer.errors, status: :unprocessable_entity }
    #   end
    # end
    if @customer.update(customer_params)
      flash.notice = "The customer record was updated successfully."
      redirect_to @customer
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :phone, :email)
    end

    def catch_not_found(e)
      Rails.logger.debug("We had a not found exception.")
      flash.alert = e.to_s
      redirect_to customers_path
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found

  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /s/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:product_name, :product_count, :customer_id)
    end

    def catch_not_found(e)
      Rails.logger.debug("We had a not found exception.")
      flash.alert = e.to_s
      redirect_to orders_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">
  <p>
    <strong>Full name:</strong>
    <%= customer.full_name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= customer.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= customer.email %>
  </p>

  <% if customer.orders.empty? %>
    <p><strong>There are no orders for this customer.</strong></p>
  <% else %>
    <h2>Orders</h2>
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Product name</th>
          <th>Product count</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% customer.orders.each do |order| %>
          <tr>
            <td><i class="fas fa-atom"></i></td>
            <td><%= order.product_name %></td>
            <td><%= order.product_count %></td>
            <td><%= link_to 'Show', order, class: "btn btn-primary" %></td>
            <td><%= link_to 'Edit', edit_order_path(order), class: "btn btn-primary" %></td>
            <td><%= button_to 'Destroy', order, method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: "btn btn-primary" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

</div>

app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :first_name, class: "form-label" %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :last_name, class: "form-label" %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :phone, class: "form-label" %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :email, class: "form-label" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Show this customer", @customer, class: "btn btn-primary" %> |
  <%= link_to "Back to customers", customers_path, class: "btn btn-primary" %>
</div>

app/views/customers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Customers</h1>

<div id="customers">
  <% @customers.each do |customer| %>
    <%= render customer %>
    <p>
      <%= link_to "Show this customer", customer, class: "btn btn-primary" %>
    </p>
  <% end %>
</div>

<%= link_to "New customer", new_customer_path, class: "btn btn-primary" %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Back to customers", customers_path, class: "btn btn-primary" %>
</div>

app/views/customers/show.html.erb
<div class="card shadow p-3 mb-5 bg-white rounded">
  <p style="color: green"><%= notice %></p>

  <%= render @customer %>
</div>

<div>
  <%= link_to "Edit this customer", edit_customer_path(@customer), class: "btn btn-primary" %> |
  <%= link_to "Back to customers", customers_path, class: "btn btn-primary" %>

  <%= button_to "Destroy this customer", @customer, method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>R7Validations</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
      <div class="container-fluid mb-0">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Customers
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'List Customers', customers_path, class: "dropdown-item" %></li>
              <li><%= link_to 'New Customer', new_customer_path, class: "dropdown-item" %></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Orders
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'List Orders', orders_path, class: "dropdown-item" %></li>
              <li><%= link_to 'New Order', new_order_path, class: "dropdown-item" %></li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>

    <div class="banner">
      <div class="banner-background mt-4 p-5 bg-primary text-white rounded">My Banner Title</div>
    </div>

    <% if flash[:alert].present? %>
      <p class="my_alert"><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/customer_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>R7Validations</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if flash[:alert].present? %>
      <p class="my_alert"><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :product_name, style: "display: block" %>
    <%= form.text_field :product_name %>
  </div>

  <div class="mb-3">
    <%= form.label :product_count, style: "display: block" %>
    <%= form.number_field :product_count, in: 1..1000 %>
  </div>

  <div class="mb-3">
    <%= form.label :customer_id, "Customer", style: "display: block" %>
    <%= form.collection_select :customer_id, Customer.all, :id, :full_name, include_blank: true %>
  </div>

  <div class="mb-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>Product name:</strong>
    <%= order.product_name %>
  </p>

  <p>
    <strong>Product count:</strong>
    <%= order.product_count %>
  </p>

  <p>
    <strong>Customer:</strong>
    <%= order.customer.full_name %>
  </p>
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order, class: "btn btn-primary" %> |
  <%= link_to "Back to orders", orders_path, class: "btn btn-primary" %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
  <% @orders.each do |order| %>
    <%= render order %>
    <p>
      <%= link_to "Show this order", order, class: "btn btn-primary" %>
    </p>
  <% end %>
</div>

<%= link_to "New order", new_order_path, class: "btn btn-primary" %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path, class: "btn btn-primary" %>
</div>

app/views/orders/show.html.erb
<div class="card shadow p-3 mb-5 bg-white rounded">
  <p style="color: green"><%= notice %></p>

  <%= render @order %>
</div>

<div>
  <%= link_to "Edit this order", edit_order_path(@order), class: "btn btn-primary" %> |
  <%= link_to "Back to orders", orders_path, class: "btn btn-primary" %>

  <%= button_to "Destroy this order", @order, method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: "btn btn-primary" %>
</div>